git:
  depth: 5

language: node_js

node_js:
  - "10"

install:
  - npm ci

before_script:
  - curl --silent https://v4.ifconfig.co/

script:
  - npm run all-with-coverage

after_success:
  - npm run coveralls

notifications:
  email:
    - joshua@mervine.net
    - bootstrap@maxcdn.com

cache:
  directories:
    - "$HOME/.npm"
